### ISSUE TITLE
pivc hanging

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/pb-git#7]
The repos under pivc are having lots of problems. I'm not sure who to send this to, so I'm trying this list.

Here is an example of a build which took 10s of minutes to 'git clone' ConsensusCore and now seems to be hung cloning pblaa:

  http://jenkins:8080/job/Mainline_pbsmrtpipe/303/console

```
cd pivc; git submodule update --init --recursive
+ cd pivc
+ git submodule update --init --recursive
Submodule 'pbccs' (git://github.com/PacificBiosciences/pbccs) registered for path 'pbccs'
Submodule 'pbconsensus' (https://KEY@github.com/PacificBiosciences/ConsensusCore) registered for path 'pbconsensus'
Submodule 'pblaa' (https://KEY@github.com/PacificBiosciences/pblaa) registered for path 'pblaa'
Submodule 'pbsparse' (https://KEY@github.com/PacificBiosciences/pbsparse) registered for path 'pbsparse'
Submodule 'seqan' (https://github.com/PacificBiosciences/seqan.git) registered for path 'seqan'
Cloning into 'pbccs'...
Submodule path 'pbccs': checked out '7d55cbb7c96fc8c0f92ccc6eff9fd234f83dfab6'
Cloning into 'pbconsensus'...
Submodule path 'pbconsensus': checked out '8cb71402e474c03072dc389e6ad35f7f0e352f33'
Cloning into 'pblaa'...

(spinner)
```

The problem is a triple combination:
* lustre
* http:// transfer (instead of git:// or ssh://)
* API keys

E.g.

* git clone https://KEY@github.com/PacificBiosciences/pblaa

or

* git clone https://KEY@github.com/PacificBiosciences/ConsensusCore

Either of those can hang about 2/3 through "Receiving objects". They often succeed if they are simply restarted. Basically, they have large packfiles. I think GitHub sometimes throttles them when using the slow http protocol, by dropping the connection temporarily.

When 'git clone' succeeds, the size of bytes received jumps suddenly from 2MB to 4MB, and again from 4MB to 6MB, at the same % where it sometimes hangs. So this is an oddity in GitHub server behavior. I have better luck in /tmp, probably because the partial download file (.git/objects/tmp_pack_mdkEw6) grows more easily in /tmp. I think in lustre, the slow sequential write causes a significant delay, so we're too frequently re-establishing a dropped connection, which means re-verifying the API key.

I see several possible solutions:

A) Build in /tmp
For a VM, this might not make a difference. Does anyone know?

B) Use ssh keys.
This is non-trivial to set up for Jenkins builds. I wouldn't want to try.

C) Make the repos public.

D) Try to chop up the packfiles in GitHub.
I haven't found a way.

E) Try git-2.1.0
This didn't help in my testing, unfortunately.

F) Implement a timeout with re-try.
This is very common at Amazon. We cannot do this with git-submodules, but it's pretty easy with pb-git. Here is the ongoing ticket for me and Lance:
*  http://bugzilla.nanofluidics.com/show_bug.cgi?id=28480
*  https://github.com/PacificBiosciences/pb-git

G) Local mirrors
This works well, and it should be feasible soon with pb-git.

H) Rebase, eliminating large files.
​This means breaking old p4 submits, as old SHA1s would become invalid.​ But maybe that's ok.​

I found a way to list the largest files stored in a repo:
*  https://stubbisms.wordpress.com/2009/07/10/git-script-to-show-largest-pack-objects-and-trim-your-waist-line/
*  http://stevelorek.com/how-to-shrink-a-git-repository.html

ConsensusCore:
```
All sizes are in kB's. The pack column is the size of the object, compressed, inside the pack file.
size  pack  SHA                                       location
2005  1960  6f91c31ec08aae321600339f2b133891750621c0  extra/gmock-1.6.0.zip
1235  1234  ea4b8dce8bbc009d051a9f7837a4e1d561ca940c  extra/google-perftools-1.8.3.tar.gz
811   722   173ac612e353aeadc2a71a103969246cda70ea00  doc/Presentations/BrownBag2012/presentation.pdf
811   116   4f3804f703c5e672f06efdf6357995a559eeab02  third-party/gmock-1.7.0/gtest/gtest.h
541   90    e8dd7fc3d2f10512505111c323fab3a28d18b801  third-party/gmock-1.7.0/gmock/gmock.h
413   104   1a63a8ce7eec6b7ae560bb42cd190dec59b7c1d7  third-party/gmock-1.7.0/gmock-gtest-all.cc
349   238   20756ad4b8ed27a0f87fcd4b9afc0eddb001a324  doc/Presentations/QuiverPracticum/quiver-practicum.pdf
156   101   b9b71a4e9ba4ebf4ac31ec762715f5c3d0887335  doc/Presentations/BrownBag2012/img/block-diagram.graffle
149   27    558c831feeb92ec0dcc3b70b5762f533b784f19b  src/C++/Logging/easylogging++.h
130   39    1ceb7c157a1a3762eb954bd6815edffa14bead76  tools/cpplint.py
```

pblaa:
```
All sizes are in kB's. The pack column is the size of the object, compressed, inside the pack file.
size  pack  SHA                                       location
2275  2258  3bc160da68151714734c8f1f945f04941369bd09  third-party/seqan-library-2.0.0/share/doc/seqan/html/img/list.pdf
787   132   4f3804f703c5e672f06efdf6357995a559eeab02  third-party/gmock-1.7.0/gtest/gtest.h
657   20    0066526e71b46c369e16592ddf42666076941c71  third-party/seqan-library-2.0.0/share/doc/seqan/html/list.html
462   96    e8dd7fc3d2f10512505111c323fab3a28d18b801  third-party/gmock-1.7.0/gmock/gmock.h
416   380   9c28143ce5c43cbc935ff069b250f4aab9e6606d  third-party/seqan-library-2.0.0/share/doc/seqan/html/img/strands.png
413   104   1a63a8ce7eec6b7ae560bb42cd190dec59b7c1d7  third-party/gmock-1.7.0/gmock-gtest-all.cc
347   44    7e0df98fb6e6f94ec58359a458575833f7cd89b5  third-party/seqan-library-2.0.0/include/seqan/basic/boost_preprocessor_subset.h
342   42    617c1becd69f3391397eb1cba2e3ae1da5ddbfa6  third-party/seqan-library-2.0.0/share/doc/seqan/html/js/search.data.js
297   76    8d7836a675077438891081149338fcf1f3c32237  third-party/seqan-library-2.0.0/share/doc/seqan/html/lib/jquery-bbq/shared/jquery-ui-1.7.2/js/jquery-ui-1.7.2.js
229   63    66b1d9b8212f1ca5365521fdfe4025776d1d8437  third-party/cpplint/cpplint.py
```
Anyway, I don't know the best solution.

**Comment by pb-cdunn** [comment]
This is for tracking. Lance is working on something for this. We can post updates here. Or I'll just close this when it's fixed.

**Comment by nlhepler** [comment]
Thanks @pb-cdunn, I'm going to work on ConsensusCore and pblaa (it's a rebase) after I get the replacement ConsensusCore into the works. Almost there. =)
